#!/bin/bash

Nsec=${1:-10}

qstat_has_w=$(man qstat 2>/dev/null | grep "\[\-w\]" | wc -l)

cmd="qstat -w -u $USER"
if [[ ${qstat_has_w} -eq 0 ]]; then
    # Try without qstat -w option
    watch -n "${Nsec}" ${cmd/-w/}
else
    watch -n "${Nsec}" ${cmd}
fi

exit 0
