#!/bin/bash

Nsec=${1:-10}

cmd="qstat -w -u $USER"
${cmd} 2>/dev/null
if [[ $? -ne 0 ]]; then
    # Try without qstat -w option
    watch -n "${Nsec}" ${cmd/-w/}
else
    watch -n "${Nsec}" ${cmd}
fi

exit 0
