#!/bin/bash
set -e

Nsec="${1:-10}"
passed_args=
if [ "$#" -gt 0 ]; then
    shift
    passed_args="$@"
fi

script="./cs.status"
if [[ ! -e "${script}" ]]; then
    script="$(ls ./cs.status.[0-9]*)"
fi
Nfound=$(echo ${script} | wc -w)
if [[ "${Nfound}" -ne 1 ]]; then
    echo "${Nfound} matches found for ./cs.status.[0-9]*" >&2
    exit 1
fi

cmd="watch -n ${Nsec} ${script} ${passed_args}"
echo $cmd
$cmd

exit 0
